// src/components/ClickCounter.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
const count = ref<number>(0)
const countMessage = computed(() => '回数: ' + count.value)
</script>

<template>
  <div>
    <div>{{ countMessage }}</div>
    <button @click="count++">クリック！</button>
    <button @click="count = 0">リセット！</button>
  </div>
</template>

<style></style>

// src/components/ClickCounter.tsx
import { useState } from "react"

function ClickCounter() {
	const [count, setCount] = useState<number>(0)
	return (
		<div>
			<div>回数： {count}</div>
			<button onClick={() => setCount(count + 1)}>クリック！</button>
			<button onClick={() => setCount(0)}>リセット！</button>
		</div>
	)
}

export default ClickCounter
